### ISSUE TITLE
Mavenize the library

### ISSUE THREAD

**Issue by azam** [sile/sanmoku#1]
Hi
Any plans to convert this library to a maven project, and posting it to a public maven nexus?
Best regards,
Azam

**Comment by sile** [comment]
I have no plan at the moment.
But if you need it and can wait until a few weeks, I will try to mavenize the library.

**Comment by azam** [comment]
It is a good thing IMO to eventually have it available in a public maven repo, but currently setting the jar in a custom local maven repo met my requirements, so there is no urgent need for it to be mavenized. 

Thank you for the reply though.

**Comment by sile** [comment]
Thank you for your reply.
It sounds good to mavenize sanmoku, but I can't afford the time for a while.
I would like to try it when I have free time.
